services:
  app:
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: npx ts-node index.js

  db:
    ports:
      - "5433:5432"

  nginx:
    profiles:
      - donotstart
